### PR TITLE
HBL, BL, SIL etc

### PR DESCRIPTION
**Pull request by Bisanabi**

### CODE REVIEW

**Review by DerrickPoh — APPROVED** [review]

**Comment by Bisanabi** [comment]
Hi Derrick,Thanks for rushing this out.  There were 404 Errors for the new pages :https://sure.nlb.gov.sg/schools/learn/https://sure.nlb.gov.sg/schools/hxn-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/academic-skills-workshop/https://sure.nlb.gov.sg/schools/teachers-cfn-workshop/Please see screenshots attached. Thanks. Damien 
-------- Original message --------From: DerrickPoh ***@***.***> Date: 30/07/2021  17:44  (GMT+08:00) To: isomerpages/nlb-sure ***@***.***> Cc: Bisanabi ***@***.***>, Author ***@***.***> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83) 
Merged #83 into master.

**Comment by Bisanabi** [comment]
Hi Derrick, I managed to isolate the issues and submitted a new pull request. Thanks. Damien 
-------- Original message --------From: damienwang ***@***.***> Date: 30/07/2021  19:12  (GMT+08:00) To: isomerpages/nlb-sure ***@***.***>, isomerpages/nlb-sure ***@***.***>, ***@***.***, ***@***.*** Cc: Author ***@***.***> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83) Hi Derrick,Thanks for rushing this out.  There were 404 Errors for the new pages :https://sure.nlb.gov.sg/schools/learn/https://sure.nlb.gov.sg/schools/hxn-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/academic-skills-workshop/https://sure.nlb.gov.sg/schools/teachers-cfn-workshop/Please see screenshots attached. Thanks. Damien -------- Original message --------From: DerrickPoh ***@***.***> Date: 30/07/2021  17:44  (GMT+08:00) To: isomerpages/nlb-sure ***@***.***> Cc: Bisanabi ***@***.***>, Author ***@***.***> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83) 
Merged #83 into master.

**Comment by DerrickPoh** [comment]
Hi Damien,

Approved and merged.


Thanks,
Derrick

**Comment by Bisanabi** [comment]
Thanks!
-------- Original message --------From: DerrickPoh ***@***.***> Date: 02/08/2021  05:16  (GMT+08:00) To: isomerpages/nlb-sure ***@***.***> Cc: Bisanabi ***@***.***>, Author ***@***.***> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83) 

Hi Damien,







Approved and merged.











Thanks,



Derrick







From: Bisanabi ***@***.***>



Sent: Friday, 30 July 2021 9:21 PM



To: isomerpages/nlb-sure ***@***.***>



Cc: Derrick POH (NLB) ***@***.***>; State change ***@***.***>



Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83)







Hi Derrick, I managed to isolate the issues and submitted a new pull request. Thanks. Damien



-------- Original message --------From: damienwang ***@***.***<mailto:***@***.***>> Date: 30/07/2021 19:12 (GMT+08:00) To: isomerpages/nlb-sure ***@***.***<mailto:***@***.***>>, isomerpages/nlb-sure ***@***.***<mailto:***@***.***>>, ***@***.***<mailto:***@***.***>, ***@***.***<mailto:***@***.***> Cc: Author ***@***.***<mailto:***@***.***>> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83) Hi Derrick,Thanks for rushing this out.  There were 404 Errors for the new pages :https://sure.nlb.gov.sg/schools/learn/https://sure.nlb.gov.sg/schools/hxn-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/tng-virtual-tour/https://sure.nlb.gov.sg/schools/academic-skills-workshop/https://sure.nlb.gov.sg/schools/teachers-cfn-workshop/Please see screenshots attached. Thanks. Damien -------- Original message --------From: DerrickPoh ***@***.***<mailto:***@***.***>> Date: 30/07/2021 17:44 (GMT+08:00) To: isomerpages/nlb-sure ***@***.***<mailto:***@***.***>> Cc: Bisanabi ***@***.***<mailto:***@***.***>>, Author ***@***.***<mailto:***@***.***>> Subject: Re: [isomerpages/nlb-sure] HBL, BL, SIL etc (#83)



Merged #83 into master.

**Pull request merged**
